version: '3.9'
services:
  api:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - db

  ai-engine:
    build: ./ai
    volumes:
      - ./ai:/usr/src/ai
    command: ["python","-u","capture_engine/orchestrator.py"]

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/next-app:/usr/src/app
    depends_on:
      - api

  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: escudo
      POSTGRES_USER: escudo
      POSTGRES_DB: escudo_db
    ports:
      - "5432:5432"
